import { Request, Response } from 'express';
import { StatusCodes } from 'http-status-codes';
import prisma from '../config/db';
import { AppError } from '../utils/AppError';
import { successResponse } from '../utils/response.util';
import { storageService } from '../services/storage/storage.service';
import { mentionService } from '../services/mention.service';

import { getSectionOwner } from '../utils/section.util';
import { Type, Section, Status } from '@prisma/client';
import { semanticSearchService } from '../services/search/semantic-search.service';

/* ---------- CREATE POST ---------- */
export const createPost = async (req: Request, res: Response) => {
  const { title, description, type, section, isUseCase, linkedEntityType, linkedEntityId, campaignId } = req.body;
  const authorId = req.user!.id;

  // Handbook B8: only allow tagging to an ACTIVE campaign. Silently drop otherwise.
  let resolvedCampaignId: number | undefined;
  if (campaignId) {
    const cid = Number(campaignId);
    if (Number.isInteger(cid) && cid > 0) {
      const c = await prisma.campaign.findUnique({ where: { id: cid }, select: { status: true } });
      if (c?.status === 'ACTIVE') resolvedCampaignId = cid;
    }
  }

  let attachmentData = null;
  if (req.file) {
    try {
      const result = await storageService.upload(
        req.file.buffer,
        req.file.originalname,
        req.file.mimetype,
        'POST_ATTACHMENT',
        false
      );
      attachmentData = {
        url: result.url,
        filename: req.file.originalname,
      };
    } catch (storageErr: any) {
      console.error('Storage upload failed:', storageErr);
      throw new AppError(
        storageErr?.message || 'Upload failed. Please try again.',
        StatusCodes.BAD_REQUEST,
        'UPLOAD_FAILED'
      );
    }
  }

  // postNumber is generated by the `generate_loop_post_number` Postgres trigger
  // (migration 20260708120000_state_machine_triggers). Do not compute it here.

  const ownerId = await getSectionOwner(section as Section);

  let post;
  try {
    post = await prisma.post.create({
      data: {
        title,
        description,
        type,
        section,
        isUseCase: isUseCase || false,
        linkedEntityType,
        linkedEntityId,
        campaignId: resolvedCampaignId,
        ownerId,
        authorId,
        status: Status.OPEN,
        attachments: attachmentData ? {
          create: [{
            url: attachmentData.url,
            filename: attachmentData.filename,
            mimeType: req.file!.mimetype,
          }]
        } : undefined
      },
      include: { author: { select: { id: true, name: true, role: true, avatarUrl: true } }, attachments: true },
    });
  } catch (error: any) {
    console.error('[createPost] Prisma create failed:', error);
    throw error;
  }

  // Fire-and-forget side effects — never let these crash the main response
  Promise.all([
    mentionService.processMentions({ text: description, authorId, postId: post.id }).catch(e =>
      console.warn('processMentions failed:', e)
    ),
    ownerId && ownerId !== authorId
      ? notificationService.createNotification({
          userId: ownerId,
          type: 'ASSIGNMENT', // Using ASSIGNMENT type for ownership alert for now
          actorId: authorId,
          postId: post.id,
        }, undefined).catch(e => console.warn('owner notification failed:', e))
      : Promise.resolve(),
    // Handbook P4 · index for semantic search. No-op when embeddings disabled.
    semanticSearchService.indexPostAsync(post.id, `${post.title}\n\n${post.description}`),
  ]).catch(() => {});

  return successResponse(res, 'Post created successfully', post, {}, StatusCodes.CREATED);
};

import { feedService } from '../services/feed.service';
import { getFeedSchema, getCommentsSchema } from '../validations/v1/feed.validation';

/* ---------- GET FEED ---------- */
export const getFeed = async (req: Request, res: Response) => {
  // We already validate this in the route using our middleware, but type casting is nice.
  // Actually, since we're using validate middleware, req.query is already parsed correctly!
  const query = req.query as any;

  const result = await feedService.getFeed({
    cursor: query.cursor,
    limit: query.limit,
    type: query.type,
    section: query.section,
    status: query.status,
    ownerId: query.ownerId,
    authorId: query.authorId,
    search: query.search,
    needResponse: query.needResponse,
    campaignId: query.campaignId,
    viewerId: req.user!.id,
  });

  return successResponse(res, 'Feed retrieved', result.items, {
    nextCursor: result.nextCursor,
    hasMore: result.hasMore,
    total: result.total
  });
};

/* ---------- GET SINGLE POST ---------- */
export const getPost = async (req: Request, res: Response) => {
  const id = Number(req.params.id);
  
  if (isNaN(id)) {
    throw new AppError('Invalid post ID', StatusCodes.BAD_REQUEST, 'INVALID_ID');
  }

  // We explicitly AVOID fetching recursive comments here to prevent payload explosion
  const post = await prisma.post.findUnique({
    where: { id },
    include: {
      author: { select: { id: true, name: true, role: true, avatarUrl: true } },
      owner: { select: { id: true, name: true, role: true, avatarUrl: true } },
      assignee: { select: { id: true, name: true, role: true, avatarUrl: true } },
      reactions: true,
      attachments: true,
      department: { select: { id: true, name: true, slug: true } },
      workflowMetrics: { select: { slaStatus: true, aiSummaryCache: true } },
      campaign: { select: { id: true, title: true, status: true, endsAt: true } },
      _count: { select: { comments: { where: { parentId: null } }, votes: true } },
      votes: { where: { userId: req.user!.id }, select: { userId: true } },
    },
  });

  if (!post) {
    throw new AppError('Post not found', StatusCodes.NOT_FOUND, 'POST_NOT_FOUND');
  }

  // Handbook C1 · surface vote state to the client. Keep the raw votes array
  // out of the response — clients only need count + whether *this* user voted.
  const { votes, _count, ...rest } = post as any;
  const hydrated = {
    ...rest,
    _count,
    voteCount: _count?.votes ?? 0,
    hasVoted: Array.isArray(votes) && votes.length > 0,
  };

  return successResponse(res, 'Post retrieved', hydrated);
};

import { notificationService } from '../services/notification.service';

import { workflowService } from '../services/workflow.service';
import { auditService } from '../services/audit.service';
import { eventBus, INTERNAL_EVENTS } from '../services/events/internal.emitter';

/* ---------- UPDATE POST STATUS (AND ASSIGNEE) ---------- */
export const updateStatus = async (req: Request, res: Response) => {
  const id = Number(req.params.id);
  const { status, assigneeId, resolution, resolutionReason, buildIssueUrl, canonicalAnswer } = req.body;
  const actorId = req.user!.id;

  if (isNaN(id)) {
    throw new AppError('Invalid post ID', StatusCodes.BAD_REQUEST, 'INVALID_ID');
  }

  // Fetch current post to check assignment idempotency
  const currentPost = await prisma.post.findUnique({
    where: { id },
    select: { assigneeId: true, departmentId: true, type: true }
  });

  if (!currentPost) {
    throw new AppError('Post not found', StatusCodes.NOT_FOUND, 'POST_NOT_FOUND');
  }

  let post: any = currentPost;

  // 1. Guarded Workflow Transition
  if (status) {
    // This will throw if the transition is mathematically invalid
    post = await workflowService.transitionStatus(id, status as Status, actorId, {
      resolution,
      resolutionReason,
      buildIssueUrl,
    });

    // Handbook D2: when resolving a Question with a canonical answer inline,
    // create the comment and mark it canonical so PostDetailPage can hoist it.
    if (canonicalAnswer && status === 'RESOLVED' && currentPost.type === 'QUESTION') {
      const created = await prisma.comment.create({
        data: { postId: id, authorId: actorId, content: canonicalAnswer, isCanonical: true },
      });
      // Best-effort mention/notification processing; failures shouldn't fail the resolve.
      mentionService
        .processMentions({ text: canonicalAnswer, authorId: actorId, commentId: created.id })
        .catch((err) => console.error('Mention processing failed for canonical answer', err));
    }
  }

  // 2. Assigment Logic
  if (assigneeId !== undefined && assigneeId !== null && assigneeId !== currentPost.assigneeId) {
    const parsedAssigneeId = Number(assigneeId);
    const assignmentOp = prisma.post.update({
      where: { id },
      data: { assigneeId: parsedAssigneeId }
    });

    const auditOp = auditService.buildAssignmentChangeAudit(actorId, id, {
      fromAssigneeId: currentPost.assigneeId,
      toAssigneeId: parsedAssigneeId,
    });

    let auditLog;
    [post, auditLog] = await prisma.$transaction([assignmentOp, auditOp]);

    // Phase 3A: Decoupled notification & realtime
    eventBus.emit(INTERNAL_EVENTS.POST_UPDATED, {
      postId: id,
      departmentId: currentPost.departmentId,
      assigneeId: parsedAssigneeId,
      actorId,
      changes: { assigneeId: parsedAssigneeId },
      auditLog
    });

    if (parsedAssigneeId !== actorId) {
      await notificationService.createNotification({
        userId: parsedAssigneeId,
        type: 'ASSIGNMENT',
        actorId,
        postId: id,
      }, undefined);
    }
  }

  return successResponse(res, 'Post updated successfully', post);
};

/* ---------- UPDATE POST CONTENT ---------- */
export const updatePost = async (req: Request, res: Response) => {
  const id = Number(req.params.id);
  const { title, description, category, tags, priority, assigneeId, departmentId } = req.body;
  const userId = req.user!.id;

  if (isNaN(id)) {
    throw new AppError('Invalid post ID', StatusCodes.BAD_REQUEST, 'INVALID_ID');
  }

  const existing = await prisma.post.findUnique({
    where: { id },
    include: { attachments: true },
  });

  if (!existing) {
    throw new AppError('Post not found', StatusCodes.NOT_FOUND, 'POST_NOT_FOUND');
  }

  if (existing.authorId !== userId) {
    throw new AppError('Forbidden. You can only edit your own posts.', StatusCodes.FORBIDDEN, 'FORBIDDEN');
  }

  // Handle attachment removal (supports single or multiple IDs from multipart form)
  const rawRemoveIds = req.body.removeAttachmentId;
  const removeIds: number[] = Array.isArray(rawRemoveIds)
    ? rawRemoveIds.map(Number)
    : rawRemoveIds
      ? [Number(rawRemoveIds)]
      : [];

  for (const attId of removeIds) {
    const attachment = existing.attachments.find((a) => a.id === attId);
    if (attachment) {
      const key = storageService.extractKey(attachment.url);
      await storageService.delete(key).catch((e) => console.warn('Failed to delete attachment file:', e));
      await prisma.attachment.delete({ where: { id: attachment.id } });
    }
  }

  // Handle new attachment upload
  if (req.file) {
    try {
      const result = await storageService.upload(
        req.file.buffer,
        req.file.originalname,
        req.file.mimetype,
        'POST_ATTACHMENT',
        false
      );
      await prisma.attachment.create({
        data: {
          url: result.url,
          filename: req.file.originalname,
          mimeType: req.file.mimetype,
          postId: id,
        },
      });
    } catch (storageErr: any) {
      throw new AppError(
        storageErr?.message || 'Upload failed. Please try again.',
        StatusCodes.BAD_REQUEST,
        'UPLOAD_FAILED'
      );
    }
  }

  const updateData: Record<string, unknown> = {};
  if (title !== undefined) updateData.title = title;
  if (description !== undefined) updateData.description = description;
  if (category !== undefined) updateData.category = category;
  if (tags !== undefined) updateData.tags = tags;
  if (priority !== undefined) updateData.priority = priority;
  if (assigneeId !== undefined) updateData.assigneeId = assigneeId;
  if (departmentId !== undefined) updateData.departmentId = departmentId;

  const post = await prisma.post.update({
    where: { id },
    data: updateData,
    include: {
      author: { select: { id: true, name: true, role: true, avatarUrl: true } },
      assignee: { select: { id: true, name: true, role: true, avatarUrl: true } },
      attachments: true,
      department: { select: { id: true, name: true, slug: true } },
      reactions: true,
      _count: { select: { comments: { where: { parentId: null } }, reactions: true } },
    },
  });

  if (description !== undefined) {
    mentionService.processMentions({ text: description, authorId: userId, postId: id }).catch((e) =>
      console.warn('processMentions failed:', e)
    );
  }

  // Handbook P4 · re-index embedding whenever title or description changes.
  if (title !== undefined || description !== undefined) {
    semanticSearchService
      .indexPostAsync(id, `${post.title}\n\n${post.description}`)
      .catch(() => {});
  }

  return successResponse(res, 'Post updated successfully', post);
};

/* ---------- GET POST COMMENTS (PAGINATED) ---------- */
export const getPostComments = async (req: Request, res: Response) => {
  const postId = Number(req.params.id);
  const query = req.query as any;

  if (isNaN(postId)) {
    throw new AppError('Invalid post ID', StatusCodes.BAD_REQUEST, 'INVALID_ID');
  }

  const result = await feedService.getPostComments(postId, query.cursor, query.limit);

  return successResponse(res, 'Comments retrieved', result.items, {
    nextCursor: result.nextCursor,
    hasMore: result.hasMore
  });
};


/* ---------- REACT TO POST ---------- */
export const reactToPost = async (req: Request, res: Response) => {
  const postId = Number(req.params.id);
  const { emoji } = req.body;
  const userId = req.user!.id;

  const existing = await prisma.reaction.findUnique({
    where: { userId_postId_emoji: { userId, postId, emoji } },
  });

  if (existing) {
    await prisma.reaction.delete({ where: { id: existing.id } });
    return successResponse(res, 'Reaction removed', { removed: true });
  } else {
    const reaction = await prisma.reaction.create({
      data: { userId, postId, emoji },
    });
    return successResponse(res, 'Reaction added', reaction, {}, StatusCodes.CREATED);
  }
};

/* ---------- VOTE ON POST (toggle) ---------- */
// Handbook C1 · one vote per user per post. Composite PK on `Vote` enforces
// it at the DB level; this endpoint just toggles.
export const votePost = async (req: Request, res: Response) => {
  const postId = Number(req.params.id);
  if (!Number.isInteger(postId) || postId <= 0) {
    throw new AppError('Invalid post ID', StatusCodes.BAD_REQUEST, 'INVALID_ID');
  }
  const userId = req.user!.id;

  const existing = await prisma.vote.findUnique({
    where: { postId_userId: { postId, userId } },
  });

  if (existing) {
    await prisma.vote.delete({ where: { postId_userId: { postId, userId } } });
    const voteCount = await prisma.vote.count({ where: { postId } });
    return successResponse(res, 'Vote removed', { hasVoted: false, voteCount });
  }

  await prisma.vote.create({ data: { postId, userId } });
  const voteCount = await prisma.vote.count({ where: { postId } });
  return successResponse(res, 'Vote recorded', { hasVoted: true, voteCount }, {}, StatusCodes.CREATED);
};

/* ---------- DELETE POST ---------- */
export const deletePost = async (req: Request, res: Response) => {
  const id = Number(req.params.id);
  const post = await prisma.post.findUnique({
    where: { id },
    include: { attachments: true },
  });
  
  if (!post) {
    throw new AppError('Post not found', StatusCodes.NOT_FOUND, 'POST_NOT_FOUND');
  }
  
  if (post.authorId !== req.user!.id && req.user!.role !== 'FOUNDER' && req.user!.role !== 'ADMIN') {
    throw new AppError('Forbidden. You cannot delete this post.', StatusCodes.FORBIDDEN, 'FORBIDDEN');
  }

  // Clean up attachment files from storage
  for (const attachment of post.attachments) {
    const key = storageService.extractKey(attachment.url);
    await storageService.delete(key).catch((e) =>
      console.warn(`Failed to delete attachment file ${key}:`, e)
    );
  }
  
  await prisma.post.delete({ where: { id } });
  return successResponse(res, 'Post deleted successfully');
};

/* ---------- GET STATS ---------- */
export const getStats = async (req: Request, res: Response) => {
  const userId = req.user!.id;

  const [totalActive, myActiveTasks, needReview, completed] = await Promise.all([
    // Total active posts across the entire platform
    prisma.post.count({ where: { status: { not: Status.RESOLVED } } }),
    // Tasks assigned to me (owned) that are not RESOLVED
    prisma.post.count({ where: { ownerId: userId, status: { not: Status.RESOLVED } } }),
    // Posts waiting for review (we can use OPEN as an approximation for now)
    prisma.post.count({ where: { status: Status.OPEN } }),
    // Total posts I have authored or been assigned to that are RESOLVED
    prisma.post.count({
      where: {
        status: Status.RESOLVED,
        OR: [{ authorId: userId }, { ownerId: userId }],
      },
    }),
  ]);

  return successResponse(res, 'Stats retrieved', {
    totalActive,
    myActiveTasks,
    needReview,
    completed,
  });
};

/* ---------- GET SLA HEALTH ---------- */
// Admin/Founder only. Surfaces the "black-hole rate" — the share of currently-Open posts
// past the 48h acknowledge window with no acknowledgedAt — plus slaStatus counts and
// average time-to-acknowledge on posts that were acknowledged.
export const getSlaHealth = async (req: Request, res: Response) => {
  const role = req.user!.role;
  if (role !== 'ADMIN' && role !== 'FOUNDER') {
    throw new AppError('SLA dashboard is restricted to Admin/Founder', StatusCodes.FORBIDDEN, 'FORBIDDEN');
  }

  const ACK_WINDOW_MS = 48 * 60 * 60 * 1000;
  const windowCutoff = new Date(Date.now() - ACK_WINDOW_MS);

  const [openTotal, blackHoleCount, statusHealthy, statusAtRisk, statusBreached, ackSample] = await Promise.all([
    prisma.post.count({ where: { status: Status.OPEN } }),
    prisma.post.count({
      where: { status: Status.OPEN, acknowledgedAt: null, createdAt: { lt: windowCutoff } },
    }),
    prisma.workflowMetrics.count({ where: { slaStatus: 'HEALTHY' } }),
    prisma.workflowMetrics.count({ where: { slaStatus: 'AT_RISK' } }),
    prisma.workflowMetrics.count({ where: { slaStatus: 'BREACHED' } }),
    prisma.post.findMany({
      where: { acknowledgedAt: { not: null } },
      select: { createdAt: true, acknowledgedAt: true },
      orderBy: { acknowledgedAt: 'desc' },
      take: 500,
    }),
  ]);

  const ackDeltas = ackSample
    .map((p) => (p.acknowledgedAt ? p.acknowledgedAt.getTime() - p.createdAt.getTime() : null))
    .filter((n): n is number => n !== null && n >= 0);
  const avgTimeToAcknowledgeMs = ackDeltas.length
    ? Math.round(ackDeltas.reduce((s, n) => s + n, 0) / ackDeltas.length)
    : null;

  const blackHoleRate = openTotal > 0 ? blackHoleCount / openTotal : 0;

  return successResponse(res, 'SLA health retrieved', {
    openTotal,
    blackHoleCount,
    blackHoleRate,
    slaStatusCounts: {
      HEALTHY: statusHealthy,
      AT_RISK: statusAtRisk,
      BREACHED: statusBreached,
    },
    avgTimeToAcknowledgeMs,
    sampleSize: ackDeltas.length,
  });
};

/* ---------- GET LOOP HEALTH (Admin dashboard) ---------- */
// Handbook C4 · Admin dashboard. Extends /sla-health with time-to-resolve,
// need-response count, a 30d black-hole rate, and a per-section breakdown.
export const getLoopHealth = async (req: Request, res: Response) => {
  const role = req.user!.role;
  if (role !== 'ADMIN' && role !== 'FOUNDER') {
    throw new AppError('Loop health dashboard is restricted to Admin/Founder', StatusCodes.FORBIDDEN, 'FORBIDDEN');
  }

  const ACK_WINDOW_MS = 48 * 60 * 60 * 1000;
  const now = Date.now();
  const ackCutoff  = new Date(now - ACK_WINDOW_MS);
  const thirtyDaysAgo = new Date(now - 30 * 24 * 60 * 60 * 1000);

  const [
    openTotal,
    needResponseCount,
    blackHoleCount,
    blackHole30d,
    open30d,
    statusHealthy,
    statusAtRisk,
    statusBreached,
    ackSample,
    resolvedSample,
    sectionCounts,
    sectionOpenCounts,
    sectionBreachedCounts,
  ] = await Promise.all([
    prisma.post.count({ where: { status: Status.OPEN } }),
    prisma.post.count({ where: { status: Status.OPEN, acknowledgedAt: null } }),
    prisma.post.count({ where: { status: Status.OPEN, acknowledgedAt: null, createdAt: { lt: ackCutoff } } }),
    // 30-day rolling: breached (as recorded by cron) among posts opened in the window
    prisma.post.count({
      where: { createdAt: { gte: thirtyDaysAgo }, workflowMetrics: { slaStatus: 'BREACHED' } },
    }),
    prisma.post.count({ where: { createdAt: { gte: thirtyDaysAgo } } }),
    prisma.workflowMetrics.count({ where: { slaStatus: 'HEALTHY' } }),
    prisma.workflowMetrics.count({ where: { slaStatus: 'AT_RISK' } }),
    prisma.workflowMetrics.count({ where: { slaStatus: 'BREACHED' } }),
    prisma.post.findMany({
      where: { acknowledgedAt: { not: null } },
      select: { createdAt: true, acknowledgedAt: true },
      orderBy: { acknowledgedAt: 'desc' },
      take: 500,
    }),
    prisma.workflowMetrics.findMany({
      where: { completedAt: { not: null }, updatedAt: { gte: thirtyDaysAgo } },
      select: { createdAt: true, completedAt: true, post: { select: { createdAt: true } } },
      orderBy: { completedAt: 'desc' },
      take: 500,
    }),
    prisma.post.groupBy({ by: ['section'], _count: { _all: true } }),
    prisma.post.groupBy({ by: ['section'], where: { status: Status.OPEN }, _count: { _all: true } }),
    prisma.post.groupBy({
      by: ['section'],
      where: { workflowMetrics: { slaStatus: 'BREACHED' } },
      _count: { _all: true },
    }),
  ]);

  const ackDeltas = ackSample
    .map((p) => (p.acknowledgedAt ? p.acknowledgedAt.getTime() - p.createdAt.getTime() : null))
    .filter((n): n is number => n !== null && n >= 0);
  const avgTimeToAcknowledgeMs = ackDeltas.length
    ? Math.round(ackDeltas.reduce((s, n) => s + n, 0) / ackDeltas.length)
    : null;

  const resolveDeltas = resolvedSample
    .map((m) =>
      m.completedAt && m.post ? m.completedAt.getTime() - m.post.createdAt.getTime() : null,
    )
    .filter((n): n is number => n !== null && n >= 0);
  const avgTimeToResolveMs = resolveDeltas.length
    ? Math.round(resolveDeltas.reduce((s, n) => s + n, 0) / resolveDeltas.length)
    : null;

  const blackHoleRate     = openTotal > 0 ? blackHoleCount / openTotal : 0;
  const blackHoleRate30d  = open30d > 0 ? blackHole30d / open30d : 0;

  const openBySection = new Map(sectionOpenCounts.map((r) => [r.section, r._count._all]));
  const breachedBySection = new Map(sectionBreachedCounts.map((r) => [r.section, r._count._all]));
  const perSection = sectionCounts
    .map((r) => ({
      section: r.section,
      total: r._count._all,
      open: openBySection.get(r.section) ?? 0,
      breached: breachedBySection.get(r.section) ?? 0,
    }))
    .sort((a, b) => b.open - a.open);

  return successResponse(res, 'Loop health retrieved', {
    openTotal,
    needResponseCount,
    blackHoleCount,
    blackHoleRate,
    blackHoleRate30d,
    slaStatusCounts: {
      HEALTHY: statusHealthy,
      AT_RISK: statusAtRisk,
      BREACHED: statusBreached,
    },
    avgTimeToAcknowledgeMs,
    avgTimeToResolveMs,
    ackSampleSize: ackDeltas.length,
    resolveSampleSize: resolveDeltas.length,
    perSection,
    generatedAt: new Date().toISOString(),
  });
};
